package com.mica.music.media.usb

internal enum class UsbOutputPhase {
    IDLE,
    REQUESTED,
    OPENING,
    ACTIVE,
    RELEASING,
    FAILED,
}

internal data class UsbOutputFailure(
    val stage: String,
    val message: String,
    val fallbackToSharedPcm: Boolean = false,
)

/** Session-scoped transport observations timestamped by a monotonic clock. */
internal data class UsbRuntimeHealth(
    val sampledAtElapsedRealtimeMs: Long,
    val completedFrames: Long,
    val bufferedFrames: Long,
    val underrunBytes: Long,
    val transportErrorCode: Int,
    val playbackRequested: Boolean,
    val sourceConsumptionActive: Boolean,
    val bufferCapacityFrames: Long? = null,
    val minimumBufferedFrames: Long? = null,
    val acceptedPcmBytes: Long? = null,
    val previousSuccessfulWriteGapUs: Long? = null,
    val maximumSuccessfulWriteGapUs: Long? = null,
    val previousDataCompletionGapUs: Long? = null,
    val maximumDataCompletionGapUs: Long? = null,
    val previousFeedbackCompletionGapUs: Long? = null,
    val maximumFeedbackCompletionGapUs: Long? = null,
    val totalPollTimeouts: Long? = null,
    val maximumConsecutivePollTimeouts: Long? = null,
    val invalidFeedbackPacketCount: Long? = null,
    val dataPacketErrorCount: Long? = null,
    val currentFeedbackQ16: Long? = null,
    val minimumFeedbackQ16: Long? = null,
    val maximumFeedbackQ16: Long? = null,
    val maximumFeedbackStepQ16: Long? = null,
    val trustedFeedbackQ16: Long? = null,
    val feedbackFilterInterventionCount: Long? = null,
    val scheduledPacketCount: Long? = null,
    val scheduledFrameCount: Long? = null,
    val outOfNominalRequestCount: Long? = null,
    val maximumConsecutiveOutOfNominalRequests: Long? = null,
    val minimumFramesPerPacket: Long? = null,
    val maximumFramesPerPacket: Long? = null,
    val maximumPacketFrameStep: Long? = null,
    val scheduleDeviationFrames: Long? = null,
    val observedPcmFrames: Long? = null,
    val zeroPcmFrameCount: Long? = null,
    val maximumConsecutiveZeroPcmFrames: Long? = null,
    val repeatedPcmFrameCount: Long? = null,
    val maximumConsecutiveRepeatedPcmFrames: Long? = null,
    val duplicatePcmRequestCount: Long? = null,
    val maximumConsecutiveDuplicatePcmRequests: Long? = null,
    val maximumAdjacentSampleDelta: Long? = null,
    val maximumRequestBoundarySampleDelta: Long? = null,
)

/** Runtime facts; consumers must not infer these from preferences. */
internal data class PlaybackOutputFacts(
    val generation: Long = 0L,
    val phase: UsbOutputPhase = UsbOutputPhase.IDLE,
    val request: UsbOutputRequest? = null,
    val runtimeHandle: UsbAudioRuntimeHandle? = null,
    val negotiatedFormat: UsbPcmFormat? = null,
    val attached: Boolean = false,
    val permission: UsbPermissionState = UsbPermissionState.UNKNOWN,
    val claimed: Boolean = false,
    val exclusive: Boolean = false,
    val signalExact: Boolean = false,
    val activeDsp: Set<String> = emptySet(),
    val runtimeHealth: UsbRuntimeHealth? = null,
    val failure: UsbOutputFailure? = null,
)
